sudo: required

services:
  - docker

stages:
  - build
  - promote

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - export TEMP_IMAGE="howtoadhd/travis-dump:howtoadhd-cavalcade-runner-$TRAVIS_COMMIT"

jobs:
  include:

    - stage: build
      before_script:
        - docker pull howtoadhd/php-base:latest-cli
      script:
        - docker build --no-cache -t $TEMP_IMAGE .
      after_success:
        - docker push $TEMP_IMAGE

    - stage: promote
      before_script:
        - docker pull $TEMP_IMAGE
        - docker tag $TEMP_IMAGE howtoadhd/cavalcade-runner:latest
      script:
        - if [ $TRAVIS_PULL_REQUEST == "false" ]; then
            docker tag $TEMP_IMAGE "howtoadhd/cavalcade-runner:$TRAVIS_BRANCH";
            docker push howtoadhd/cavalcade-runner:$TRAVIS_BRANCH;
          fi

        - if [ $TRAVIS_PULL_REQUEST == "false" ] && [ $TRAVIS_BRANCH == "master" ]; then
            docker tag $TEMP_IMAGE "howtoadhd/cavalcade-runner:latest";
            docker push howtoadhd/cavalcade-runner:latest;
          fi

notifications:
  webhooks:
    - https://h2a-hubot.herokuapp.com/webhooks/travis
